routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::get('register/agreement', 'Auth\RegisterController@show')->name('register.agreement');
// Route::get('register/moneyTrade/{moneyTrade}', 'MoneyTradeController@store')->name('moneyTrade.store')->middleware('auth');
// Route::get('register/moneytrade/show/{moneyTrade}', 'MoneyTradeController@show')->name('register.moneytrade.show');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('moneytrade', 'MoneyTradeController')->middleware('auth');
Route::get('/moneytrade', 'MoneyTradeController@store')->middleware('auth');
Route::get('/moneytrade/registration', 'MoneyTradeController@index')->name('mt.registration')->middleware('auth');

app/MoneyTrade.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class MoneyTrade extends Model
{
    //  /**
    //  * The attributes that are mass assignable.
    //  *
    //  * @var array
    //  */
    // protected $fillable = [
    //     'bank', 'email', 'mt_first_name', 'mt_last_name', 'mt_password', 'mt_account', 'mt_deposit', 'mt_leverage',
    // ];

    // /**
    //  * The attributes that should be hidden for arrays.
    //  *
    //  * @var array
    //  */
    // protected $hidden = [
    //     'password', 'remember_token',
    // ];

    // /**
    //  * The attributes that should be cast to native types.
    //  *
    //  * @var array
    //  */
    // protected $casts = [
    //     'email_verified_at' => 'datetime',
    // ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'email', 'username', 'first_name', 'last_name', 'dob', 'landline', 'mobile', 'password', 'question1', 'question1_answer', 'question2', 'question2_answer',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/MoneyTradeController.php
<?php

namespace App\Http\Controllers;

use App\MoneyTrade;
use Illuminate\Http\Request;



class MoneyTradeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home.mt-registration');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'bank' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255'],
            'mt_first_name' => ['required', 'string', 'max:255'],
            'mt_last_name' => ['required', 'string', 'max:255'],
            'mt_password' => ['required', 'string', 'min:8', 'confirmed'],
            'mt_account' => ['required', 'string', 'max:255'],
            'mt_deposit' => ['required', 'string', 'max:255'],
            'mt_leverage' => ['required', 'string', 'max:255'],


        ]);

        $moneyTrade = new MoneyTrade();

        $moneyTrade->mt_number = uniqid('MTNumber-');

        $moneyTrade->bank = $request->input('bank');
        $moneyTrade->email = $request->input('email');
        $moneyTrade->mt_first_name = $request->input('mt_first_name');
        $moneyTrade->mt_last_name = $request->input('mt_last_name');
        $moneyTrade->mt_password = $request->input('mt_password');
        $moneyTrade->mt_account = $request->input('mt_account');
        $moneyTrade->mt_deposit = $request->input('mt_deposit');
        $moneyTrade->mt_leverage = $request->input('mt_leverage');

        $moneyTrade->user_id = auth()->id();

        $moneyTrade->save();

        return redirect()->route('home')->withMessage('MoneyTrade Account Created');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\MoneyTrade  $moneyTrade
     * @return \Illuminate\Http\Response
     */
    public function show(MoneyTrade $moneyTrade)
    {
        return view('home.money-app');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\MoneyTrade  $moneyTrade
     * @return \Illuminate\Http\Response
     */
    public function edit(MoneyTrade $moneyTrade)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\MoneyTrade  $moneyTrade
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, MoneyTrade $moneyTrade)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\MoneyTrade  $moneyTrade
     * @return \Illuminate\Http\Response
     */
    public function destroy(MoneyTrade $moneyTrade)
    {
        //
    }
}

resources/views/home/money-app.blade.php
@extends('layouts.app')

@section('content')
                        <!-- Moneytrade Modal -->
                        <div class="modal fade" id="moneytradeModal" role="dialog">
                            <div class="modal-dialog">

                              <!-- Modal content-->
                              <div class="modal-content">
                                <div class="modal-header">
                                  <h4 class="modal-title">Connect to an Account</h4>
                                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>
                                <div class="modal-body">
                                  <p><center> Authorization allows to get access to your Money account </center></p>

                                  <div class="form-group row">
                                      <label for="mt_email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                      <div class="col-md-6">
                                          <input id="mt_email" type="mt_email" class="form-control @error('mt_email') is-invalid @enderror" name="mt_email" value="{{ old('mt_email') }}" required autocomplete="mt_email" autofocus>

                                          @error('mt_email')
                                              <span class="invalid-feedback" role="alert">
                                                  <strong>{{ $message }}</strong>
                                              </span>
                                          @enderror
                                      </div>
                                  </div>

                                  <div class="form-group row">
                                      <label for="mt_password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                      <div class="col-md-6">
                                          <input id="mt_password" type="mt_password" class="form-control @error('mt_password') is-invalid @enderror" name="mt_password" required autocomplete="current-password">

                                          @error('mt_password')
                                              <span class="invalid-feedback" role="alert">
                                                  <strong>{{ $message }}</strong>
                                              </span>
                                          @enderror
                                      </div>
                                  </div>

                                  <div class="form-group row">
                                      <label for="bank" class="col-md-4 col-form-label text-md-right">{{ __('Bank') }}</label>

                                      <div class="col-md-6">
                                          <input id="bank" type="text" class="form-control @error('bank') is-invalid @enderror" name="bank" value="MoneyTrade Bank" required autocomplete="current-bank" readonly>

                                          @error('bank')
                                              <span class="invalid-feedback" role="alert">
                                                  <strong>{{ $message }}</strong>
                                              </span>
                                          @enderror
                                      </div>
                                  </div>

                                </div>
                                <div class="modal-footer">
                                  <button type="button" class="btn btn-default" data-toggle="modal" data-target="#registerModal">Register</button>
                                  <button type="button" class="btn btn-default">Login</button>
                                  {{-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> --}}
                                </div>
                              </div>

                            </div>
                          </div>
@endsection

resources/views/home/mt-registration.blade.php
@extends('layouts.app')

@section('content')

<h2>OK</h2>
    {{-- <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h4 class="modal-title">Open an Account</h4>
                    </div>
                <div class="card-body">

                    <form action="{{route('moneytrade.store')}}" method="post">
                        @csrf

                        <h3><b>Personal Details</b></h3>
                        <p><center> To open an account, please fill out the following fields:</center></p>

                        <div class="form-group row">
                            <label for="bank" class="col-md-4 col-form-label text-md-right">{{ __('Bank') }}</label>

                            <div class="col-md-6">
                                <input id="bank" type="text" class="form-control @error('bank') is-invalid @enderror" name="bank" value="MoneyTrade Bank" required autocomplete="current-bank" readonly>

                                @error('bank')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') }}" required autocomplete="email" autofocus>

                                @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mt_first_name" class="col-md-4 col-form-label text-md-right">{{ __('First Name') }}</label>

                            <div class="col-md-6">
                                <input id="mt_first_name" type="text" class="form-control @error('mt_first_name') is-invalid @enderror" name="mt_first_name" value="{{ old('mt_first_name') }}" placeholder="First name of the account owner" required autocomplete="mt_first_name" autofocus>

                                @error('mt_first_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mt_last_name" class="col-md-4 col-form-label text-md-right">{{ __('Last Name') }}</label>

                            <div class="col-md-6">
                                <input id="mt_last_name" type="text" class="form-control @error('mt_last_name') is-invalid @enderror" name="mt_last_name" value="{{ old('mt_last_name') }}" placeholder="Last name of the account owner" required autocomplete="mt_last_name" autofocus>

                                @error('mt_last_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mt_password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                            <div class="col-md-6">
                                <input id="mt_password" type="password" class="form-control @error('mt_password') is-invalid @enderror" name="mt_password" placeholder="Minimum of 8 characters" required autocomplete="new-mt_password">

                                @error('mt_password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mt_password-confirm" class="col-md-4 col-form-label text-md-right">{{ __('Confirm Password') }}</label>

                            <div class="col-md-6">
                                <input id="mt_password-confirm" type="password" class="form-control" name="password_confirmation" placeholder="Minimum of 8 characters" required autocomplete="new-password">
                                <div class="checkbox">
                                    <label><input type="checkbox" value="" checked>Use hedge in investment and trading</label>
                                </div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mt_account" class="col-md-4 col-form-label text-md-right">{{ __('Account Type') }}</label>

                            <div class="col-md-6">
                                <select name="mt_account" class="form-control @error('mt_account') is-invalid @enderror">
                                    <option value="forex-php">forex-php</option>
                                    <option value="forex-usd">forex-usd</option>
                                </select>
                                @error('mt_account')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mt_deposit" class="col-md-4 col-form-label text-md-right">{{ __('Deposit') }}</label>

                            <div class="col-md-6">
                                <input id="mt_deposit" type="text" class="form-control @error('mt_deposit') is-invalid @enderror" name="mt_deposit" value="2500" placeholder="Last name of the policy owner" required autocomplete="mt_deposit" autofocus >

                                @error('mt_deposit')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="mt_leverage" class="col-md-4 col-form-label text-md-right">{{ __('Leverage') }}</label>

                            <div class="col-md-6">
                                <select name="mt_leverage" class="form-control @error('mt_leverage') is-invalid @enderror">
                                    <option value="l100">100</option>
                                    <option value="l500">500</option>
                                    <option value="l1000">1000</option>
                                </select>
                                @error('mt_leverage')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror

                                <div class="checkbox">
                                    <label><input type="checkbox" value="" checked>I agree with the terms and conditions for opening an account and the data protection policy.</label>
                                </div>
                            </div>
                        </div>

                        <div class="modal-footer">
                            <button type="submit" class="btn btn-default">Next</button>
                            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                        </div>
                    </form>
                </div>
                </div>
            </div>
        </div>
    </div> --}}
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    {{-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script> --}}


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">
    {{-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> --}}

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register.agreement') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        {{-- display success message --}}
        @if (session()->has('message'))
        <div class="alert alert-success text-center" role="alert">
            {{session('message')}}
        </div>
        @endif


        {{-- display error message --}}
        @if (session()->has('error'))
            <div class="alert alert-danger text-center" role="alert">
                {{session('error')}}
            </div>
        @endif

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>